### ISSUE TITLE
Port to Windows

### ISSUE THREAD

**Issue by chfast** [czepluch/pysecp256k1#11]
I'm working on porting pyethapp to Windows. Can you help me with porting this package to Windows? Or help me finding a replacement?

**Comment by czepluch** [comment]
Yes, I will help, when I get back from vacation next week. We are however looking into using https://github.com/ludbb/secp256k1-py repo for pyethapp instead of this one.

**Comment by chfast** [comment]
https://github.com/ludbb/secp256k1-py/pull/6
